#!/usr/bin/env bash
# Script: anyhooksencrypt
# Author: Ricardo Malnati
# Creation Date: 2023-10-15
# Description: Generates .anyhooksopenai.enc file for storing OpenAI API Key
# Dependencies: curl, openssl, anyhooksdisplaymsg

openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout AnyHooks-key.pem -out AnyHooks-cer.pem -subj "/C=BR/ST=Distrito Federal/L=Brasilia/O=Ricardo Malnati/OU=DevOps/CN=Ricardo Malnati/emailAddress=ricardomalnati@gmail.com" && security import AnyHooks-key.pem -k ~/Library/Keychains/login.keychain && security add-trusted-cert -d -r trustRoot -k ~/Library/Keychains/login.keychain AnyHooks-cer.pem
security find-identity -v -p codesigning
codesign --sign "Ricardo Malnati" --options "runtime" .git/hooks/commit-msg
