#!/bin/bash
# Script: rc/anyhookscore
# Author: Ricardo Malnati
# Creation Date: 2023-10-22
# Description: Manages hooks, encryption, and language settings for AnyHooks
# Dependencies: bash

# Debug function
echoDebugMsg() {
  [ "$1" = true ] && shift && echo "🐛 Debug: $@"
}
# Error function
echoErrorMsg() {
  echo "❌ Error: $@"
  exit 9999
}
# Log function
echoLogMsg() {
  echo "ℹ️  Info: $@"
}
# Warning function
echoWarningMsg() {
  echo "⚠️  Warning: $@"
}

validateRequiredString() { 
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Entering ${FUNCNAME[0]} ${@}"
  local string_to_check="$1"
  local error_message_append="$2"
  if [ ! -z "$string_to_check" ]; then
    echoDebugMsg "String $string_to_check found!"
    return 0
  else
    if [ -z "$error_message_append" ]; then
      echoErrorMsg "String $string_to_check not found, $error_message_append!"
    else
      echoErrorMsg "String $string_to_check not found!"
    fi
  fi
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Exiting ${FUNCNAME[0]} ${@}"
}

validateRequiredFileExistence() { 
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Entering ${FUNCNAME[0]} ${@}"
  validateRequiredString "$1 param at ${FUNCNAME[0]} ${@}"
  local file_to_check="$1"
  local error_message_append="$2"
  if [ -f "$file_to_check" ]; then
    echoDebugMsg "File $file_to_check found at ${FUNCNAME[0]}."
    return 0
  else
    if [ -z "$error_message_append" ]; then
      echoErrorMsg "File $string_to_check not found, $error_message_append!"
    else
      echoErrorMsg "File $string_to_check not found!"
    fi
  fi
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Exiting ${FUNCNAME[0]} ${@}"
}

validateFileExecutable() { 
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Entering ${FUNCNAME[0]} ${@}"
  validateRequiredFileExistence "$1" " param at ${FUNCNAME[0]} ${@}"
  local file_to_check="$1"
  local error_message_append="$2"
  if [ -x "$file_to_check" ]; then
    echoDebugMsg "File $file_to_check found at ${FUNCNAME[0]}."    
  else
    if [ -z "$error_message_append" ]; then
      echoErrorMsg "File $string_to_check not found, $error_message_append!"
      return 0
    else
      echoErrorMsg "File $string_to_check not found!"
    fi
  fi
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Exiting ${FUNCNAME[0]} ${@}"
}

validateFileReadable() { 
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Entering ${FUNCNAME[0]} ${@}"
  validateRequiredFileExistence "$1" "1 param at ${FUNCNAME[0]} ${@}"
  local file_to_check="$1"
  local error_message_append="$2"
  if [ -r "$file_to_check" ]; then
    echoDebugMsg "File $file_to_check found at ${FUNCNAME[0]}."
    return 0
  else
    if [ -z "$error_message_append" ]; then
      echoErrorMsg "File $string_to_check not found, $error_message_append!"
    else
      echoErrorMsg "File $string_to_check not found!"
    fi
  fi
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Exiting ${FUNCNAME[0]} ${@}"
}

validateFileWritable() { 
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Entering ${FUNCNAME[0]} ${@}"
  validateRequiredFileExistence "$1" "1 param at ${FUNCNAME[0]} ${@}"
  local file_to_check="$1"
  local error_message_append="$2"
  if [ -w "$file_to_check" ]; then
    echoDebugMsg "File $file_to_check found."
    return 0
  else
    if [ -z "$error_message_append" ]; then
      echoErrorMsg "File $string_to_check not found, $error_message_append!"
    else
      echoErrorMsg "File $string_to_check not found!"
    fi
  fi
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Exiting ${FUNCNAME[0]} ${@}"
}

validateRequiredDirectoryExistence() { 
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Entering ${FUNCNAME[0]} ${@}"
  local path_to_check="$1"
  local error_message_append="$2"
  if [ -d "${path_to_check}" ]; then
    echoDebugMsg "Directory ${path_to_check} found."
    return 0
  else
    if [ -z "$error_message_append" ]; then
      echoErrorMsg "Directory ${string_to_check} not found, ${error_message_append}!"
    else
      echoErrorMsg "Directory ${string_to_check} not found!"
    fi
  fi
  echoDebugMsg ${ANYHOOKS_DEBUG_MODE} "Exiting ${FUNCNAME[0]} ${@}"
}

getUserHomeDir() {
  echo "$(eval echo ~$USER)"
}

# if declare -F echoDebugMsg > /dev/null; then
#     echo -e "\nechoDebugMsg exists.\n"
# else
#     echo -e "\nechoDebugMsg does not exist.\n"
# fi

# # Loading Debug function
# echoDebugMsg true "Loading Debug function"
# # Loading Error function
# echoErrorMsg "Loading Error function"
# # Loading Log function
# echoLogMsg "Loading Log function"
# # Loading Warning function
# echoWarningMsg "Loading Warning function"