#!/bin/bash
# Script: rc/anyhooksdisplaymsg
# Author: Ricardo Malnati
# Creation Date: 2023-10-18
# Description: Manages messages for AnyHooks

# Defines the debug state for this script, the flag come from --debug
IS_DEBUG_MODE=false

# Debug function
display_debug_message() {
  [ "$IS_DEBUG_MODE" = true ] && echo "🐛 Debug: $@"
}
# Error function
display_error_message() {
  echo "❌ Error: $@"
}
# Log function
display_log_message() {
  echo "ℹ️  Info: $@"
}
# Warning function
display_warning_message() {
  echo "⚠️  Warning: $@"
}

display_debug_message "Loading rc/anyhooksdisplaymsg"